{{- if and .Values.cleanupCustomResource }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cert-manager-umbrella.fullname" . }}-operator-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "cert-manager-umbrella.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "cert-manager-umbrella.fullname" . }}-operator-cleanup
      labels:
{{ include "cert-manager-umbrella.labels" . | indent 8 }}
    spec:
    {{- if .Values.global.rbac.create }}
      serviceAccountName: {{ include "call-nested" (list . "cert-manager" "cert-manager.serviceAccountName") }}
    {{- end }}
      containers:
        - name: kubectl
          image: "{{ .Values.hyperkubeImage.repository }}:{{ .Values.hyperkubeImage.tag }}"
          imagePullPolicy: "{{ .Values.hyperkubeImage.pullPolicy }}"
          command:
          - /bin/sh
          - -c
          - >
              kubectl delete certificate   --all;
              kubectl delete challenge     --all;
              kubectl delete clusterissuer --all;
              kubectl delete issuer        --all;
              kubectl delete order         --all;
              sleep 10;
              kubectl delete crd certificates.certmanager.k8s.io;
              kubectl delete crd challenges.certmanager.k8s.io;
              kubectl delete crd clusterissuers.certmanager.k8s.io;
              kubectl delete crd issuers.certmanager.k8s.io;
              kubectl delete crd orders.certmanager.k8s.io;
      restartPolicy: OnFailure
{{- end }}
