{{- if .Values.gitConfig.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.fullname" . }}-git-config
  labels:
    app: {{ template "atlantis.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config: {{ .Values.gitConfig.config | b64enc }}
{{- end -}}
