{{- if .Values.gitSsh.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlantis.fullname" . }}-git-ssh
  labels:
    app: {{ template "atlantis.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config: {{ .Values.gitSsh.sshConfig | b64enc }}
  id_rsa_ci_bot: {{ .Values.gitSsh.sshPrivateKey | b64enc }}
{{- end -}}
