{{- if and ( .Values.monitoring.serviceMonitor.enabled ) ( .Values.monitoring.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cert-manager-umbrella.labels" . | nindent 4 }}
  name: {{ template "cert-manager-umbrella.fullname" . }}
spec:
  ports:
    - name: metrics
      port: 9402
      protocol: TCP
      targetPort: 9402
  selector:
    app: {{ include "call-nested" (list . "cert-manager" "cert-manager.name") }}
    release: {{ .Release.Name }}
  type: ClusterIP
{{- end }}
