name: gitub-pages-push
on:
  push:
    branches:
    - mater
jobs:
  build:
    name: Pages
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: "dist-repo"
